### ISSUE TITLE
transparent tiff

### ISSUE THREAD

**Issue by elgubenis** [galkahana/HummusJS#123]
id like to writeImage a transparent tiff, but i get this error: TypeError: Unable to end PDF
when i use this tiff: https://www.dropbox.com/s/g9krrehydqid2ch/636f85f0-b762-11e6-b401-951da7f96ed8.TIF?dl=0

but when i use a tif from your tests like this: https://www.dropbox.com/s/o9yiovn7mfweh48/CCITT_5.TIF?dl=0 it works!

maybe its because my tif has transparency?

tiffinfo gave out the following info for both tifs:

my transparent one:
```sh
TIFF Directory at offset 0x2126 (8486)
  Image Width: 530 Image Length: 215
  Resolution: 28.34, 28.34 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: RGB color
  Extra Samples: 1<assoc-alpha>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 4
  Rows/Strip: 128
  Planar Configuration: single image plane
  JPEG Tables: (289 bytes)
```

yours from the tests:
```sh
TIFF Directory at offset 0x7df0 (32240)
  Image Width: 1728 Image Length: 2376
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 4
  Photometric Interpretation: min-is-white
  FillOrder: lsb-to-msb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 2376
  Planar Configuration: single image plane
  DocumentName: Standard Input
  ImageDescription: converted PBM file
```

any idea what can be done to use my transparent tif with drawImage?

**Comment by galkahana** [comment]
transparency in tiff is not supported, but this only means that the image would have a white background. not that there would be a failure. need to debug and check.

**Comment by galkahana** [comment]
Investigated.
Well. thing is that this is not a tiff file. it's a png (if you open the file in a text editor the first 4 chars says "%png"). hummus identifies that this is not a tiff file (or any supported file type) and refuses to introduce the image into the pdf, notifying a failure.  you're getting the error only on the page write and not directly at writeImage  because of this special facet of writeImage which delays the image encoding to the page write (there's a technical story here which i'll share if you want to).

So the thing to do here is to convert it to a supported image type. As you reported to me via email, you did a good job of achieving that by embedding the tiff in a PDF file created by another software and embedding the PDF into hummus. This is the *best* way to retain image transparency in hummus (other than going and implementing it...of course :) ).

**Comment by elgubenis** [comment]
ok, funny though that tiffinfo recognized something there, id like to share how i got to work the transparent png to pdf with pdfkit + hummus, maybe in your wiki?

**Comment by galkahana** [comment]
how about you create a git for the code, and i'll refer to it from the wiki description of drawImage?
