### ISSUE TITLE
Having trouble replacing source objects

### ISSUE THREAD

**Issue by BrighTide** [galkahana/HummusJS#138]
Hi,

I'm trying to use Hummus for the purposes of redacting information out of a pdf, and hence need to make direct edits to the source streams, rather than just append overwriting changes.

As per my understanding of the replaceSourceObjects method, if I call

`
copyingContext.replaceSourceObjects({3:4});
`

the number 3 object shouldn't make it into the final document, and the number 4 object should end up in it's place.

However the following code:

```
var hummus = require('hummus');

var pdfWriter = hummus.createWriter('./ato4.pdf', {compress:false, log:'C:\\_s\\www\\node_modules\\a\\log.txt'});
var page = pdfWriter.createPage(0,0,600,800);
pdfWriter.writePage(page)
pdfWriter.end();



// create modifier to reduce page size
var modPdfWriter = hummus.createWriterToModify('./ato4.pdf');
var copyingContext = modPdfWriter.createPDFCopyingContextForModifiedFile();
var objectsContext = modPdfWriter.getObjectsContext();

var firstPageID = copyingContext.getSourceDocumentParser().getPageObjectID(0);
var newPageId = objectsContext.allocateNewObjectID();

copyingContext.replaceSourceObjects({[firstPageID]:newPageId});

//Create what will become our new page object
objectsContext.startNewIndirectObject(newPageId);
var modifiedPageObject = objectsContext.startDictionary();
var firstPageObject = copyingContext.getSourceDocumentParser().parsePage(0).getDictionary().toJSObject();

Object.getOwnPropertyNames(firstPageObject).forEach(function(element, index, array) {
  console.log(element);
  if (element != 'MediaBox') {
    modifiedPageObject.writeKey(element);
    copyingContext.copyDirectObjectAsIs(firstPageObject[element]);
  }
});

modifiedPageObject.writeKey('MediaBox');
      objectsContext
        .startArray()
        .writeNumber(0)
        .writeNumber(0)
        .writeNumber(300)
        .writeNumber(400)
        .endArray()
        .endLine()
        .endDictionary(modifiedPageObject)
        .endIndirectObject();
modPdfWriter.end();
```

produces a pdf with the original object (3) still existing. Have I misunderstood how copyingContext.replaceSourceObjects works? And if so, is there anyway to totally replace an object in the modification process (even if that modification is modifying a pdf stream, and not just a media box)?

Thanks :)

**Comment by galkahana** [comment]
Hi,
Since you are modifying a document you will get a PDF with appended changes, and not what you intended - a clean pdf without old objects.
when doing this (modifying) `replaceSourceObjects` doesn't make sense because it is only meant to be used while copying from one PDF to another. You may simply replace the call to 
`startNewIndirectObject` with `startModifiedIndirectObject`, and provide the original page ID, instead of allocating a new one. This should replace the original page.

If you want to get a clean version of the file after having modified it, use the Recrypt method, like this:

hummus.recrypt(
    './ato4.pdf',
    './ato4Clean.pdf');

[i'm telling about it here - http://pdfhummus.com/post/147451287581/hummus-1058-and-pdf-writer-updates-encryption.]

(another option is to avoid using modification altogether, and implementing something like recrypt yourself by creating a new file, copying content for the original and copying the pdf catalog of the original to the new one. then `replaceSourceObjects` makes sense, where you do pretty much what you wrote here - create a new page and mark it as a replacement. thing is, with the NodeJS version of hummus there's still no method to tell hummus to avoid creating a new catalog object and use an existing one instead (the one you are copying), so such a thing is not possible. yet).

**Comment by BrighTide** [comment]
recrypt was exactly what I was looking for, I just modified the page with the appended redactions method then recrypted it afterwards to remove the old content. Thanks so much for the help, and for the rad lib :)
