### ISSUE TITLE
unable to append page, make sure it's fine

### ISSUE THREAD

**Issue by fedyunin** [galkahana/HummusJS#62]
Hello! 

I need to join several one page PDF files into one multipage PDF file.

I tried to use basic page appending (https://github.com/galkahana/HummusJS/wiki/Embedding-pdf#basic-page-appending)

I used code from provided example. But I always got next error on attempt to execute it:

"unable to append page, make sure it's fine"

Not clear why it appears and what happens. Could you clarify it please? 
I also tried to use PDF files from '/HummusJS/tree/master/tests/TestMaterials' (as in example) - I got the same issue.

Thanks!

**Comment by galkahana** [comment]
My guess i that the target for writing is unavailable, so it cant write. Want to verify? (Or maybe something else eith the script, care to show it?).

Gal.

Hello!

I need to join several one page PDF files into one multipage PDF file.

I tried to use basic page appending (https://github.com/galkahana/HummusJS/wiki/Embedding-pdf#basic-page-appending)

I used code from provided example. But I always got next error on attempt to execute it:

"unable to append page, make sure it's fine"

Not clear why it appears and what happens. Could you clarify it please?
I also tried to use PDF files from '/HummusJS/tree/master/tests/TestMaterials' (as in example) - I got the same issue.




Thanks!

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/galkahana/HummusJS/issues/62

**Comment by fedyunin** [comment]
I checked it, but looks like all fine with access and write file. 

I created simple function for do join:

```javascript
function(files, resultPDFFileName) {
    var pdfWriter = hummus.createWriter(resultPDFFileName);
    for (var i in files) {
        var file = files[i];
      pdfWriter.appendPDFPagesFromPDF(file);
    }
    pdfWriter.end();
    return resultPDFFileName;
};
```

Where files: array of files to join (local), resultPDFFileName - name of result PDF file.

I tried just create and close file by next commands:

```javascript
 var pdfWriter = hummus.createWriter(resultPDFFileName);
 pdfWriter.end();
```

Was successfully created a empty PDF file.

**Comment by galkahana** [comment]
ok. how about figure out the difference between npm test (specifically the https://github.com/galkahana/HummusJS/blob/master/tests/AppendPagesTest.js) and your case?
i mean, does npm test succeed?

**Comment by fedyunin** [comment]
I ran test it works fine.

Then I added my own pdf files, which need to join into one. All works fine. 
I noticed that I got this issue, when I use this pdf file: http://www.orimi.com/pdf-test.pdf (just searched in google for test PDF file and took first item from search result).

Can be issues with joining files related to issues in the PDF file?

**Comment by galkahana** [comment]
When running the script with log for pdfwriter (you can add log by calling 
`hummus.createWriter('MY_PDF_FILE',{log:'MY_LOG_FILE'})`)
the log shows this:

[ 21/03/2016 22:57:19 ] PDFDocumentHandler::StartCopyingContext, Document contains an encryption dictionary. Library does not support embedding of encrypted PDF

This means that the PDF is encrypted. Hummus does not handle encrypted PDF files, which is why appending pages. if you want to expect this in advanced, hummus provides method to tell if a PDF is encrypted. see `isEncrypted` here - https://github.com/galkahana/HummusJS/wiki/Parsing.

**Comment by fedyunin** [comment]
Thank you for exlanation. Right now, clear why this issue happens. I will do appropriate checks and use logging for prevent or discover errors.

**Comment by fedyunin** [comment]
Hello! 

There is issue with join files. I can successfully join several file into one pdf file. I have several  files with filled form data. (I used hummus-js for fill fields in my pdf files). I got joined file without any filled fields. Pls see attached files. 

Code:
```javascript
function(files, pathToResultPDFFile) {
    var pathToResultFileName = pathToResultPDFFile + "_join.pdf";

    var pdfWriter = hummus.createWriter(pathToResultFileName, {
        log: "./tmp/log.txt"
    });
    for (var i in files) {
        var file = files[i];
        try {
            pdfWriter.appendPDFPagesFromPDF(file);
        }
        catch (e) {
            console.warn("Unable to join file: " + file + ", skipped.");
        }
    }
    pdfWriter.end();

    return pathToResultFileName;
};
```
[1.pdf](https://github.com/galkahana/HummusJS/files/193943/1.pdf)
[2.pdf](https://github.com/galkahana/HummusJS/files/193944/2.pdf)
[join_result.pdf](https://github.com/galkahana/HummusJS/files/193945/join_result.pdf)

Thanks!

**Comment by galkahana** [comment]
This makes sense. As appending pages only appends the pages. As you may recall the form is a global object, and not tied to a particular page.

how about you tell me a little about what you have in mind. maybe we can work around this by creating a modified version of the file with the form. In this way the form will remain.

Gal.

**Comment by fedyunin** [comment]
Ok clear, so right now just copied page content, except fields (from Acroform).

I think that, in this case need copy all form objects (filled fields) from each source file to result file. SO we will have a new PDF file which fill have Acroform objects from other files.

**Comment by galkahana** [comment]
Right.
So we need a new acroform on the fresh PDF, or modify an existing one (depends on the appending scenario). and if  I recall correctly there were also new annotations created on pages, for filled form fields, which don't get copied too by the `appendPDFPagesFromPDF` method, which only copies content and what relevant resources come out of this.

So there are 2 tasks here:

1. Create an Acroform object on the catalog object to combine the pages fields 
2. Recreate the annotations on the appended pages

The C++ library allows for extending the page writing and catalog writing phases, so it can be done easily there by adding handlers to page copying to copy annotations, and adding an acroform to the catalog. unfortunately i'm yet to expose these methods in the nodejs module. i'll put me a task here to try and get to it this week. 

What you could do for now is to have a 2nd phase to do these things, because modification module does give you access to both catalog object and the pages objects, and you can just modify them.

What you should do is:
1. Have a first phase doing the appends as you do
2. End the pdf so the file handle is released (yes, we'll need a file here, to allow a 2nd phase). 
3. Open the result pdf in a new writer for modification (you done this with the form filling project). now we can modify the page objects and the catalog.
4. Take care of task #1. modify each page object by adding an annotations entry, copying the annotations from the matching page in the original pdf from which you appended.
5. Take care of task 2. modify the catalog by creating a new acroform object (you can copy all but the fields entry from one of the PDFs you are appending from that has a form, or create a new object). Now create  a fields entry in the form which will be an accumulation of all field entries from all pages.

hope it's clear. im here for clarifications, if you want them.

Gal.

**Comment by fedyunin** [comment]
Thanks a lot for detailed descriptions. It's clear what you suggested here. I will try to implements what you suggested here. 

Thanks!

**Comment by galkahana** [comment]
@fedyunin.

published yesterday a new version that allows you to listen on page writing and catalog writing events.
This means that you can write the acroform and copy the annotations in the same pass as embedding the pages. so no need for a seconds pass.

Using the page writing event i wrote an example on how to embed a page with its annotations, which is step .1 in the solution here. it should do for what you need - https://tmblr.co/ZGAZks24UarNi

**Comment by fedyunin** [comment]
Thanks I will try out a new version and use it for join PDFs!
