### ISSUE TITLE
Pagemarks when copying a page from another PDF.

### ISSUE THREAD

**Issue by ericwenn** [galkahana/HummusJS#72]
Hey
I've been splitting a PDF into several ones for each page using this code:

```
var originalPDF = "/path/to/original/";
var targetPath = "/target/path/foo.pdf";
var pageNo = 2;
var pdfReader = hummus.createReader(originalPDF);
pdfWriter = hummus.createWriter(targetPath);
pdfWriter.createPDFCopyingContext(pdfReader).appendPDFPageFromPDF(pageNo);
pdfWriter.end();
```

However I get marks on the page, that werent in the original PDF.
This is what I mean: [page-2.pdf](https://github.com/galkahana/HummusJS/files/276368/page-2.pdf)

Is there a setting somewhere to not include this?

**Comment by galkahana** [comment]
Seems like a bug. The original page include these marks. You dont see them probably because it has a crop box defined.
The hummus appending algorithm does not copy this box, which is why you see them in the end result, as it shows the full page.
This is best handled by fixing the algorithm to also copy this box. If youll send me the original pdf, so i can verify that my solution works, ill try to get around to this today.

**Comment by galkahana** [comment]
know what, i went ahead and implemented the improved version of page append.
how about try the new version? its should have 1.0.53 as version number.

Gal.

**Comment by ericwenn** [comment]
I will test the new version as soon as possible and get back to you, thanks!
